### PR TITLE
Add api_base arg and fix a json exception when saving results

### PR DESCRIPTION
**Pull request by Bryce-Peng**
Thanks for your great project!
I'm trying on studying and rerunning this code, and have encountered several issue, so i create this PR for your consideration.

1. When saving overall analystical results, there might be some hidden nonjson files in ./output, which are automatically made by git or other apps and will lead to a json decoding exception.

2. proxy api is needed for accessibility, so I add an optional arg 'GPT_api_base' in the config template and use it in api.GPT.request()

3. there isn't a module name 'uhgeval.llm.gpt', so I modified it to 'uhgeval.llm.api' in demo.py

### CODE REVIEW

**Comment by Ki-Seki** [comment]
Thank you very much for your pull request. The first and third points you mentioned are extremely helpful. 

However, regarding the second point, the variable `GPT_api_base` seems to have no essential difference from `GPT_api_key` in my view. Could you provide an explanation of the necessity of adding this variable, including the scenarios it would involve, and why the issue cannot be resolved by using only `GPT_api_key`?

**Comment by Bryce-Peng** [comment]
> Thank you very much for your pull request. The first and third points you mentioned are extremely helpful.
> 
> However, regarding the second point, the variable `GPT_api_base` seems to have no essential difference from `GPT_api_key` in my view. Could you provide an explanation of the necessity of adding this variable, including the scenarios it would involve, and why the issue cannot be resolved by using only `GPT_api_key`?

my personal scenario as an example: 
I'm actually can't access to openai api directly for network reason, so i need to set the requested url to an proxy instead of the default value. 

in 'openai' package, the full url is like:
`abs_url = "%s%s" % (self.api_base, url)`

and the api_base is set as below: 
`api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")`

it is not nessisary for everyone, and it's alternative to set the environment value 'OPENAI_API_BASE', so i made it optional.

now I'm thinking maybe its just a very rare case, so if you have the authority to edit, you could just remove it out~ : )

**Comment by Ki-Seki** [comment]
> > Thank you very much for your pull request. The first and third points you mentioned are extremely helpful.
> > However, regarding the second point, the variable `GPT_api_base` seems to have no essential difference from `GPT_api_key` in my view. Could you provide an explanation of the necessity of adding this variable, including the scenarios it would involve, and why the issue cannot be resolved by using only `GPT_api_key`?
> 
> my personal scenario as an example: I'm actually can't access to openai api directly for network reason, so i need to set the requested url to an proxy instead of the default value.
> 
> in 'openai' package, the full url is like: `abs_url = "%s%s" % (self.api_base, url)`
> 
> and the api_base is set as below: `api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")`
> 
> it is not nessisary for everyone, and it's alternative to set the environment value 'OPENAI_API_BASE', so i made it optional.
> 
> now I'm thinking maybe its just a very rare case, so if you have the authority to edit, you could just remove it out~ : )

I understand. Now I'm ready to accept these changes to the main branch. However, it's important to note that there are differences in the interface of the [`openai-python`](https://github.com/openai/openai-python) package between versions 0.28.1 and 1.0+. In the past, changing the base URL mainly relied on the `os.environ.get` method, while in the new version, it is primarily set through `openai.base_url`. To ensure consistency and improve compatibility, I have adopted the method using `base_url` here. Therefore, the request method in the corresponding `api.py` needs to be modified. 

Are you willing to continue with these modifications and submit a new pull request? The tasks include:

1. Modify the GPT request method in `api.py` according to https://github.com/openai/openai-python?tab=readme-ov-file#module-level-client to maintain compatibility with the latest openai-python.
2. Update the version of `openai` in `requirements.py` to the latest version.

By the way, could you please share your email address with me? I am exploring potential collaborations, and we may continue working on this project together.

**Comment by Bryce-Peng** [comment]
> > > Thank you very much for your pull request. The first and third points you mentioned are extremely helpful.
> > > However, regarding the second point, the variable `GPT_api_base` seems to have no essential difference from `GPT_api_key` in my view. Could you provide an explanation of the necessity of adding this variable, including the scenarios it would involve, and why the issue cannot be resolved by using only `GPT_api_key`?
> > 
> > 
> > my personal scenario as an example: I'm actually can't access to openai api directly for network reason, so i need to set the requested url to an proxy instead of the default value.
> > in 'openai' package, the full url is like: `abs_url = "%s%s" % (self.api_base, url)`
> > and the api_base is set as below: `api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")`
> > it is not nessisary for everyone, and it's alternative to set the environment value 'OPENAI_API_BASE', so i made it optional.
> > now I'm thinking maybe its just a very rare case, so if you have the authority to edit, you could just remove it out~ : )
> 
> I understand. Now I'm ready to accept these changes to the main branch. However, it's important to note that there are differences in the interface of the [`openai-python`](https://github.com/openai/openai-python) package between versions 0.28.1 and 1.0+. In the past, changing the base URL mainly relied on the `os.environ.get` method, while in the new version, it is primarily set through `openai.base_url`. To ensure consistency and improve compatibility, I have adopted the method using `base_url` here. Therefore, the request method in the corresponding `api.py` needs to be modified.
> 
> Are you willing to continue with these modifications and submit a new pull request? The tasks include:
> 
> 1. Modify the GPT request method in `api.py` according to https://github.com/openai/openai-python?tab=readme-ov-file#module-level-client to maintain compatibility with the latest openai-python.
> 2. Update the version of `openai` in `requirements.py` to the latest version.
> 
> By the way, could you please share your email address with me? I am exploring potential collaborations, and we may continue working on this project together. @Bryce-Peng

my email address is pxh0996@163.com, and i'm willing to continue on this task.  : )

**Pull request merged**
